services:
  my-dashboard-sql:
    image: 'bitnami/postgresql:latest'
    container_name: 'my-dashboard-sql'
    volumes:
      - 'my-dashboard-sql-volume:/bitnami/postgresql'
    ports:
      - '35432:5432'
    healthcheck:
      test:
        - 'CMD-SHELL'
        - 'pg_isready -U postgres'
      interval: '5s'
      timeout: '5s'
      retries: 5
    tty: true
    restart: 'always'
    environment:
      POSTGRESQL_USERNAME: 'postgres'
      POSTGRESQL_PASSWORD: 'mydashboardpassword'
      POSTGRESQL_DATABASE: 'postgres'
volumes:
  my-dashboard-sql-volume:
    name: 'my-dashboard-sql-volume'